### ISSUE TITLE
What's exactly happening in this part? Can you 'please' explain?

### ISSUE THREAD

**Issue by Sayantan17** [FrancescoSaverioZuppichini/ResNet#3]
nn.Sequential(
block(in_channels , out_channels, *args, **kwargs, downsampling=downsampling),
*[block(out_channels * block.expansion,
out_channels, downsampling=1, *args, **kwargs) for _ in range(n - 1)]
)

**Comment by FrancescoSaverioZuppichini** [comment]
Hi, "please" is the magic word. This is a python inline for loop where I create one block after the other. Just google "inline for loop in python"

**Comment by Sayantan17** [comment]
Actually I am asking that  why you multiplied 2 blocks?
