### ISSUE TITLE
Identity Function

### ISSUE THREAD

**Issue by Shakesbeer333** [FrancescoSaverioZuppichini/ResNet#4]
Hi @FrancescoSaverioZuppichini 

I have a question about the Residual Block. I don't understand the idea behind `nn.Idenitiy()`. Why do we need this part, when sizes don't match? 

Sry for asking this simple question, but my knowledge about Deep Learning is rather small.

Thank you in advance :-)

**Comment by FrancescoSaverioZuppichini** [comment]
Hi, `nn.Identity()` does nothing (just forward the input), in this case, it is just a placeholder :)

**Comment by Shakesbeer333** [comment]
Hi @FrancescoSaverioZuppichini, so we could basically just delete it?

**Comment by FrancescoSaverioZuppichini** [comment]
Yes, it is there for consistency

**Comment by Shakesbeer333** [comment]
@FrancescoSaverioZuppichini thank you :-)

**Comment by FrancescoSaverioZuppichini** [comment]
:)
